version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: tvglobo
      POSTGRES_PASSWORD: tvglobo123
      POSTGRES_DB: youtube_crud
    ports:
      - "5433:5432"

  backend:
    build: ./Backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./Backend:/app
    command: ["wait-for-it.sh", "db:5432", "--", "python3", "app.py"]

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:
