version: "3.9"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: tvglobo
      POSTGRES_PASSWORD: tvglobo123
      POSTGRES_DB: youtube_crud
    ports:
      - "5433:5432"